feature/SPRIND-137
Sphereon-Opensource/OID4VC pull request #174
Opened 2024-12-06 23:09 UTC by zoemaas

2025-01-08 08:27 UTC, nklomp requested changes
See remarks

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/__tests__/IT.spec.ts
> +describe('RP and OP interaction should', () => {
If you are re-enabling tests, please remove the FIXME. But more importantly get in touch about what the FIXME/readme is about before re-enabling. UniResolvers are unstable in deployment. Hence the link to the ticket. By re-enabling this ticket we will again have tests failing every now and then

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/__tests__/SdJwt.spec.ts
> +describe('RP and OP interaction should', () => {
See earlier remark about enabling tests that have a TODO/FIXME

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
Cannot be correct in case a definitition_uri is passed in. These are xor, and you are only looking for the actual definition object here

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +        ...(opts.vp_token.dcql_query && { dcql_query: opts.vp_token.dcql_query }),
This is an error. Are you also sure you merged in latest PR/work from Animo to begin with? I remember making this same remark. The dcql_query needs to be brought outisde of the line 38. As the first line in the vp_token part (33-40) would also be true (!vp_token_definition_uri) in case of dcql, which would mean it would include an undefined presentation_definition all of a sudden.

So simply make a distinction between dcql and PD earlier on and based on that return the previous code/result or the dcql result.

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/URI.ts
> +      await findValidDcqlQuery({ ...authorizationRequestPayload, ...requestObjectPayload })
What is the reason for the static import change. Not like this is easier to read or anything

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/helpers/SIOPSpecVersion.ts
> +      authorizationRequestCopy.response_mode !== ResponseMode.DIRECT_POST // Post has been replaced by direct post
Why is this being changed? it is incorrect to be clear. This is a v13 validation, that had POST not direct_post

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/request-object/Payload.ts
> +    dcql_query: payload.dcql_query,
This assumes a dcql_query is always present, returning in an undefined, whilst this whole function is about removing any nulls/undefineds

2025-01-08 08:27 UTC, nklomp commented on packages/siop-oid4vp/lib/rp/RP.ts
> +      ...(opts?.dcqlQuery && !opts?.presentationDefinitions && {
Should do nothing with ! presentation definitions. It should check earlier whether both PD and DCQL are present and reject if that is the case as they are mutually exclusive

2025-01-08 10:04 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
This comes from the original PR: https://github.com/Sphereon-Opensource/OID4VC/blob/ad19797805d68855d902afcf586d521927654adc/packages/siop-oid4vp/lib/authorization-request/Payload.ts#L29-L34

2025-01-08 10:20 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +        ...(opts.vp_token.dcql_query && { dcql_query: opts.vp_token.dcql_query }),
DCQL and PD are now separated

2025-01-08 10:23 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/URI.ts
> +      await findValidDcqlQuery({ ...authorizationRequestPayload, ...requestObjectPayload })
Not my code again: https://github.com/Sphereon-Opensource/OID4VC/blob/ad19797805d68855d902afcf586d521927654adc/packages/siop-oid4vp/lib/authorization-request/URI.ts#L169

2025-01-08 11:16 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/URI.ts
> +      await findValidDcqlQuery({ ...authorizationRequestPayload, ...requestObjectPayload })
You made it your code by copying the original PR. Please address

2025-01-08 11:17 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
Yes?! You made it your code by copy pasting it. It is introduced in this PR, so it needs to be fixed

2025-01-08 13:36 UTC, zoemaas commented on packages/siop-oid4vp/lib/rp/RP.ts
> +      ...(opts?.dcqlQuery && !opts?.presentationDefinitions && {
Created the code to check whether PDs and DCQL are both present

2025-01-08 13:37 UTC, zoemaas commented on packages/siop-oid4vp/lib/__tests__/SdJwt.spec.ts
> +describe('RP and OP interaction should', () => {
Rolled it back to skip test

2025-01-08 13:37 UTC, zoemaas commented on packages/siop-oid4vp/lib/__tests__/IT.spec.ts
> +describe('RP and OP interaction should', () => {
Rolled it back to skip test

2025-01-14 11:10 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
I think you got me wrong. From the project management perspective it makes more sense to have the person who wrote the code to fix its issues because it's more efficient. (At the point I've wrote the comment above, there was an open PR and it was even reviewed). I should have only started to work on this code after the original PR was merged to avoid dependency on tickets, to reduce complexity and conflicts.

2025-01-14 11:11 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
It's addressed

2025-01-14 11:11 UTC, zoemaas commented on packages/siop-oid4vp/lib/authorization-request/URI.ts
> +      await findValidDcqlQuery({ ...authorizationRequestPayload, ...requestObjectPayload })
I think you got me wrong. From the project management perspective it makes more sense to have the person who wrote the code to fix its issues because it's more efficient. (At the point I've wrote the comment above, there was an open PR and it was even reviewed). I should have only started to work on this code after the original PR was merged to avoid dependency on tickets, to reduce complexity and conflicts. It's addressed

2025-01-14 13:19 UTC, zoemaas commented on packages/siop-oid4vp/lib/request-object/Payload.ts
> +    dcql_query: payload.dcql_query,
I think you got me wrong. From the project management perspective it makes more sense to have the person who wrote the code to fix its issues because it's more efficient. (At the point I've wrote the comment above, there was an open PR and it was even reviewed). I should have only started to work on this code after the original PR was merged to avoid dependency on tickets, to reduce complexity and conflicts. It's addressed

2025-01-14 14:50 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
No I didn't get it wrong. This is new code being I produced in this PR. If there then is an issue, you simply cannot say.. Not my problem

2025-01-17 11:21 UTC, sanderPostma requested changes
No big things found

2025-01-17 11:21 UTC, sanderPostma commented on packages/siop-oid4vp/lib/op/OP.ts
> +    dcqlQuery?: DcqlQueryResponseOpts
Better call this dcqlResponse or something

2025-01-20 16:10 UTC, sanderPostma commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
fixed

2025-01-21 09:59 UTC, sanderPostma commented on packages/callback-example/package.json
> +    "@sphereon/ssi-types": "0.32.1-feature.VDX.341.53",
I will create a follow-up PR when SSI-SDK is merged. But first we need to merge this PR because SSI-SDK also depends on this project to a greater extend.

2025-01-21 09:59 UTC, sanderPostma commented on packages/siop-oid4vp/lib/op/OP.ts
> +    dcqlQuery?: DcqlQueryResponseOpts
fixed

2025-01-21 10:02 UTC, ronal2do commented on package.json
> +    "@sphereon/ssi-types": "0.32.1-feature.VDX.341.53",
just wondering if we will keep working with packages with branch-names, after merge to developer we might fix it

2025-01-21 10:04 UTC, ronal2do commented on packages/siop-oid4vp/lib/__tests__/AuthenticationResponse.response.spec.ts
> +    /* console.log(
those comments can be removed

2025-01-21 10:07 UTC, ronal2do commented on packages/siop-oid4vp/lib/rp/RPBuilder.ts
> +      // FIXME SPRIND-144 we need to find a way in the config to select dcql vs PD without breaking OID4VC-DEMO
ok

2025-01-21 10:08 UTC, ronal2do commented on packages/siop-oid4vp/lib/rp/RP.ts
> +      ...(opts?.dcqlQuery /*&& !opts?.presentationDefinitions */&& { // FIXME presentationDefinitions will be there until we fix the OID4VC-DEMO, it wants a PD purpose field for the screens
can we address it to the SPRIND-144 or something

2025-01-21 10:09 UTC, ronal2do approved these changes

2025-01-21 10:09 UTC, ronal2do commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
I'll approve while waiting for @nklomp  input here

2025-01-21 10:32 UTC, sanderPostma commented on package.json
> +    "@sphereon/ssi-types": "0.32.1-feature.VDX.341.53",
I will take care of it, see other tickets

2025-01-21 11:15 UTC, nklomp commented on packages/siop-oid4vp/lib/authorization-request/Payload.ts
> +    const discoveryResult = PEX.definitionVersionDiscovery(opts.vp_token.presentation_definition)
> content of presentation_definition_uri and do a discovery on that? (It did not do that before)

Yes see above. Removing the URI version is play wrong. We already have a function to do this. So if it is a URI just fetch is and then you will end up with a the non URI version

2025-01-23 09:06 UTC, ronal2do approved these changes

2025-01-23 09:13 UTC, merged